version: '3.8'
services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 9080:9080
    volumes:
      - ./app/conf/nginx-core.conf:/etc/nginx/nginx.conf
      - ./app/conf/nginx-app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 9090:9090