version: '3.8'
services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 9080:9080
    depends_on:
      - backend

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 9090:9090